import json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
p={}
def add(key,value,unit,status,source,note=''):
 p[key]=dict(value=value,unit=unit,status=status,source=source,note=note)
add('total_mass',899,'kg','Documented','NASA landing press kit 2012 p.3')
add('gravity',3.71,'m/s^2','Documented','JPL planetary physical parameters; research pack')
add('wheel_radius',.25,'m','Derived','JPL Wheel Damage Table 1','Includes grousers. Smooth cylinder collision envelope.')
add('wheel_width',.4,'m','Documented','JPL Wheel Damage Table 1')
add('baseline_speed',.04,'m/s','Documented','NASA landing press kit 2012')
add('chassis_mass',699,'kg','Estimated','Mass budget','Includes locked arm, turret, mast, electronics and MMRTG. Residual after mobility bodies.')
add('rocker_mass',35,'kg each','Estimated','Provisional mass budget')
add('bogie_mass',20,'kg each','Estimated','Provisional mass budget')
add('carrier_mass',9,'kg each','Estimated','Provisional mass budget')
add('wheel_mass',9,'kg each','Estimated','Provisional mass budget','Not a NASA wheel mass measurement.')
add('drive_torque',80,'N m','Estimated','Provisional actuator model','Not flight actuator data; sensitivity 0.5x and 1.5x.')
add('drive_kp',48,'N m s/rad','Calibrated','Finite PI speed servo; settled and driven at 120/240 Hz','Numerical tuning, not flight controller gains.')
add('drive_ki',24,'N m/rad','Calibrated','Finite PI speed servo with clamp','Numerical tuning, not flight controller gains.')
add('steering_torque',200,'N m','Estimated','Provisional actuator model','Sized for rigid-cylinder static scrub; not flight data.')
add('steering_rate',.25,'rad/s','Estimated','Provisional actuator model')
add('steering_limit',1.48,'rad','Estimated','Provisional actuator travel, +/-84.8 deg')
add('steering_kp',1200,'N m/rad','Estimated','Bounded steering servo')
add('steering_kd',60,'N m s/rad','Estimated','Bounded steering servo')
add('differential_stiffness',50000,'N m/rad','Estimated','Compliant ideal gear constraint','qL+qR approaches zero; finite compliance rather than an exact gear joint.')
add('differential_damping',500,'N m s/rad','Estimated','Numerical stabilization of differential')
add('differential_torque',3000,'N m','Estimated','Coupling safety clamp')
add('acceleration',.025,'m/s^2','Estimated','Player command ramp')
add('yaw_acceleration',.02,'rad/s^2','Estimated','Player command ramp')
add('baseline_yaw_rate',.025,'rad/s','Estimated','Playable point-turn command')
add('linear_damping',.015,'1/s','Estimated','Numerical damping, not measured drag')
add('angular_damping',.025,'1/s','Estimated','Numerical damping, not measured joint friction')
add('wheel_friction',1.0,'dimensionless','Estimated','Jolt contact material; terrain chooses effective friction')
add('rock_friction',.85,'dimensionless','Estimated','Hard-ground rigid contact')
add('regolith_friction',.6,'dimensionless','Estimated','Rigid consolidated-ground approximation')
add('sand_friction',.25,'dimensionless','Estimated','Low-friction rigid sand proxy','No sinkage, shear history, compaction or embedding; not terramechanics.')
add('game_time_scale',6.0,'sim seconds/wall second','Estimated','Time acceleration','Physics tick frequency multiplied with time scale to preserve dt.')
add('physics_hz',120,'Hz','Estimated','Fixed-step integration; convergence compared at 240 Hz')
add('chassis_inertia',[170,230,180],'kg m^2 XYZ','Estimated','Lumped rectangular internal mass distribution','Applied in rover.gd. Not solid external mesh; sensitivity required.')
add('rocker_inertia',[12,14,3],'kg m^2 XYZ','Estimated','Slender-link approximation')
add('bogie_inertia',[4,5,1],'kg m^2 XYZ','Estimated','Slender-link approximation')
add('carrier_inertia',[.8,.4,.8],'kg m^2 XYZ','Estimated','Carrier lump')
add('wheel_inertia',[.56,.4,.4],'kg m^2 XYZ','Estimated','Thin-hoop axial inertia m*r^2; transverse includes width')
add('rocker_limit',.7,'rad','Estimated','Provisional travel')
add('bogie_limit',.8,'rad','Estimated','Provisional travel')
add('chassis_collision_size',[1.36,.5,1.85],'m XYZ','Estimated','Simplified body collision; asset-inspected envelope')
add('steering_readiness',.12,'rad','Estimated','Drive fades to zero while steering error exceeds 6.9 degrees')
add('floating_torque_fraction',.12,'dimensionless','Estimated','Unloaded wheel speed limiting')
add('slip_denominator_floor',.01,'m/s','Estimated','Regularization near zero speed')
add('rocker_collision_radius',.1,'m','Estimated','Simplified pivot collision sphere')
add('bogie_collision_radius',.085,'m','Estimated','Simplified pivot collision sphere')
add('carrier_collision_radius',.06,'m','Estimated','Simplified carrier collision sphere')
g=json.loads((root/'assets/geometry.json').read_text())
for name,position in g['groups'].items():
 add('origin_'+name,position,'m XYZ Godot', 'Estimated' if name=='ChassisVisual' else 'Measured from the visual asset','assets/geometry.json; NASA visual asset','Body/pivot origin; not flight CAD. Chassis origin approximates locked-equipment COM.' if name=='ChassisVisual' else 'Wheel centers or existing mechanical pivot origins; axes not certified flight data.')
(root/'engineering_parameters.json').write_text(json.dumps(p,indent=2))
